using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Photon.Core.Generator
{
    [Generator]
    public class MaterialBindingGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<GeneratorSyntaxContext> candidateClasses = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (SyntaxNode node, CancellationToken _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0 && cds.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
                transform: static (GeneratorSyntaxContext ctx, CancellationToken _) => ctx
            );

            IncrementalValueProvider<(Compilation Compilation, ImmutableArray<GeneratorSyntaxContext> Contexts)> compilationAndContexts = context.CompilationProvider.Combine(candidateClasses.Collect());
            context.RegisterSourceOutput(compilationAndContexts, Execute);
        }

        private static void Execute(SourceProductionContext spc, (Compilation Compilation, ImmutableArray<GeneratorSyntaxContext> Contexts) source)
        {
            Compilation compilation = source.Compilation;
            ImmutableArray<GeneratorSyntaxContext> contexts = source.Contexts;

            INamedTypeSymbol uniformEnumType = compilation.GetTypeByMetadataName("Photon.Core.Shader.BuildinShaderUniformType");
            if (uniformEnumType == null)
            {
                return;
            }

            foreach (GeneratorSyntaxContext ctx in contexts)
            {
                if (ctx.Node is not ClassDeclarationSyntax classDecl)
                {
                    continue;
                }

                INamedTypeSymbol classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (classSymbol == null)
                {
                    continue;
                }

                bool hasMaterialAttr = classSymbol.GetAttributes().Any(a => a.AttributeClass?.Name is "MaterialAttribute" or "Material");
                bool isMaterialBase = classSymbol.BaseType?.Name == "MaterialBase";

                if (!hasMaterialAttr || !isMaterialBase)
                {
                    continue;
                }

                if (!classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PHOTON001",
                            "材质类必须是 partial",
                            "类 {0} 必须添加 partial 关键字以支持代码生成",
                            "Photon.Generator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        classDecl.Identifier.GetLocation(),
                        classSymbol.Name));
                    continue;
                }

                string code = GeneratePartialClass(classSymbol, uniformEnumType);
                string hintName = $"{classSymbol.ContainingNamespace.ToDisplayString()}.{classSymbol.Name}.g.cs";

                spc.AddSource(hintName, SourceText.From(code, Encoding.UTF8));
            }
        }

        private static string GeneratePartialClass(INamedTypeSymbol classSymbol, INamedTypeSymbol uniformEnumType)
        {
            string ns = classSymbol.ContainingNamespace.ToDisplayString();
            string className = classSymbol.Name;

            List<IPropertySymbol> customProps = classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name is "MaterialPropertyAttribute" or "MaterialProperty"))
                .ToList();

            List<string> builtInUniformNames = uniformEnumType.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.Name != "Count")
                .Select(f => f.Name)
                .ToList();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine($@"// <auto-generated/>");
            sb.AppendLine($@"using Photon.Core.Shader;");
            sb.AppendLine($@"using System;");
            sb.AppendLine($@"namespace {ns}");
            sb.AppendLine($@"{{");

            sb.AppendLine($@"    public partial class {className}");
            sb.AppendLine($@"    {{");

            sb.AppendLine($@"        public override void InitializeUniform()");
            sb.AppendLine($@"        {{");
            sb.AppendLine($@"            propertyIndexMap.Clear();");
            sb.AppendLine($@"            int index = 0;");

            foreach (string name in builtInUniformNames)
            {
                sb.AppendLine($@"            propertyIndexMap[""{name}""] = index++;");
            }

            foreach (IPropertySymbol prop in customProps)
            {
                sb.AppendLine($@"            propertyIndexMap[""{prop.Name}""] = index++;");
            }

            sb.AppendLine($@"            shaderUniforms = new ShaderUniform[index];");
            sb.AppendLine($@"        }}");

            sb.AppendLine($@"        public override void BindUniform()");
            sb.AppendLine($@"        {{");
            sb.AppendLine($@"            if (shaderUniforms == null)");
            sb.AppendLine($@"            {{");
            sb.AppendLine($@"                return;");
            sb.AppendLine($@"            }}");

            foreach (IPropertySymbol prop in customProps)
            {
                sb.AppendLine($@"            if (propertyIndexMap.TryGetValue(""{prop.Name}"", out int idx_{prop.Name}))");
                sb.AppendLine($@"            {{");
                sb.AppendLine($@"                shaderUniforms[idx_{prop.Name}] = new ShaderUniform({prop.Name});");
                sb.AppendLine($@"            }}");
            }

            sb.AppendLine($@"        }}");
            sb.AppendLine($@"    }}");
            sb.AppendLine($@"}}");

            return sb.ToString();
        }
    }
}